language: go
sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y iputils-ping
- go get -a -installsuffix cgo -ldflags '-d -s -w' github.com/mattn/goveralls
after_success:
- sudo apt-get install -y build-essential rubygems libopenssl-ruby ruby-dev rpm
- bundle install
- make AWSnycast
- make dist
- ls -l dist/
- make coverage.out
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
go:
- 1.11
env:
- CGO_ENABLED=0 GOOS=linux
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "R6u944OuUQwy2xDcpPe6LrxcdUI4+phsOJU6oDEX8U3rMMTvuz1Mykt+IPlOYc7P7MTW5k+CaWBlw9DVxuYZa0gV9vGFoUKEXT/H4pOYahADCZkj6E+4IZGcbQgsRWWClP78PtXGpY/Q3X5HJ3IeeY9+tuJmq5wDXuDM7GV70pw="
  file:
    - AWSnycast
    - $(ls dist/awsnycast*.deb)
    - $(ls dist/awsnycast*.rpm)
  on:
    tags: true
