language: go
sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y iputils-ping
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
#script:
#- go get ./... && make test && make && make coverage.out && $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
go:
- 1.4
- 1.5
env:
- AWS_ACCESS_KEY_ID=AKIAJRYDH3TP2D3WKRNQ AWS_SECRET_ACCESS_KEY=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
deploy:
  provider: releases
  api_key:
    secure: Fsjtv/dMVNDEvrkwxxrZJR1dUf526nG70/SDVfCHKqEBrkTQqPHgymWloo3D9DHpWhBOvbqtRCPLIcy/TqRUCnviZ4HVYlUXER0r7uQXk2eKUoxu6N5DKn/J3BKZwSi3ZW9GicsDqdfhZlnrVweBPzmmcklBqAkBjpfIyynlE+Y=
  file: AWSnycast
  on:
    tags: true
