language: go

before_install:
    apt-get install -y iputils-ping

go:
  - 1.4
  - 1.5

env:
  - AWS_ACCESS_KEY_ID=AKIAJRYDH3TP2D3WKRNQ AWS_SECRET_ACCESS_KEY=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

